### ISSUE TITLE
Add support of "standalone" attribute in header declaration

### ISSUE THREAD

**Issue by pauze007** [bvn13/GpxAndroidSdk#1]
Hi,

I attempted to use a file with an unsupported attribute in the XML header. In the XML declaration, we can have the "standalone" attribute set to either "yes" or "no". However, in your code, I noticed that you only checked for "yes". Could you modify it to account for all possibilities?

https://xmlwriter.net/xml_guide/xml_declaration.shtml

**Comment by bvn13** [comment]
fixed in 1.10.3
